"""Human-readable and machine-readable research artifacts."""

from __future__ import annotations

import json
from pathlib import Path

from .research import ResearchResult


def _format_metric(value: object) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def markdown_report(result: ResearchResult, *, source: str) -> str:
    lines = [
        "# FactorLab research report",
        "",
        "This is a diagnostic report, not a live trading recommendation.",
        "",
        "## Run configuration",
        "",
    ]
    lines.extend(f"- **{key}**: `{value}`" for key, value in result.config.items())
    lines += [
        "",
        f"- **source**: `{source}`",
        "",
        "## Results",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    for key in (
        "observations",
        "total_return",
        "annualized_return",
        "annualized_volatility",
        "sharpe",
        "max_drawdown",
        "hit_rate",
        "average_turnover",
        "mean_ic",
        "icir",
        "ic_positive_ratio",
        "ic_observations",
    ):
        lines.append(f"| {key} | {_format_metric(result.metrics.get(key))} |")
    if result.split_metrics:
        lines += [
            "",
            "## Date split",
            "",
            "| Segment | Net return | Sharpe | Max drawdown |",
            "|---|---:|---:|---:|",
        ]
        for segment, metrics in result.split_metrics.items():
            lines.append(
                f"| {segment} | {_format_metric(metrics.get('total_return'))} | "
                f"{_format_metric(metrics.get('sharpe'))} | {_format_metric(metrics.get('max_drawdown'))} |"
            )
    lines += [
        "",
        "## Reading this result",
        "",
        "- `forward_return` is close(t+1) / close(t) - 1. The score is formed at t.",
        "- IC is daily Spearman rank correlation between score and next-session return.",
        "- Portfolio weights are dollar-neutral and gross 1.0; net return subtracts turnover × cost.",
        "- The final row of each ticker has no next-session return and is excluded.",
        "- Synthetic demo data is for plumbing checks only; it is not evidence of alpha.",
        "",
        "Generated by FactorLab.",
        "",
    ]
    return "\n".join(lines)


def write_artifacts(
    result: ResearchResult, output_dir: str | Path, *, source: str
) -> Path:
    """Write CSV/JSON/Markdown artifacts and an optional equity curve plot."""

    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    result.daily.to_csv(destination / "daily_returns.csv", index=False)
    result.ic_by_date.to_csv(destination / "ic_by_date.csv", index=False)
    result.weights.to_csv(destination / "weights.csv", index=False)
    (destination / "metrics.json").write_text(
        json.dumps(
            {
                "config": result.config,
                "metrics": result.metrics,
                "split_metrics": result.split_metrics,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (destination / "report.md").write_text(
        markdown_report(result, source=source), encoding="utf-8"
    )
    if not result.daily.empty:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        equity = (1.0 + result.daily["net_return"]).cumprod()
        figure, axis = plt.subplots(figsize=(9, 4.5))
        axis.plot(result.daily["date"], equity, color="#1f4e79", linewidth=1.4)
        axis.set_title("Dollar-neutral factor equity curve")
        axis.set_ylabel("Growth of 1.0")
        axis.grid(alpha=0.25)
        figure.tight_layout()
        figure.savefig(destination / "equity_curve.png", dpi=140)
        plt.close(figure)
    return destination
